name: Deploy Alertbot

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: List installed packages
        run: pip list


      - name: Check Python version
        run: python --version

      - name: Copy files to VDS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VDS_HOST }}  
          username: ${{ secrets.VDS_USER }}  
          key: ${{ secrets.SSH_KEY }}  
          port: 22  # Порт SSH, обычно 22
          source: "." 
          target: "~/rmalert"  
